default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: &development
  adapter: postgresql
  host: localhost
  port: 5432
  database: nirdb
  username: postgres
  password: postgres

test:
  <<: *default
  database: nir_test

production:
  adapter: postgresql
  host: dpg-cps6k1aj1k6c738il200-a.frankfurt-postgres.render.com
  port: 5432
  database: nirdb_f0pk
  username: almazer
  password: 6AG91hcd6dxXTFgyfNZv5ftHsIbYEk3a
