default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
    adapter: postgresql
    host: localhost
    port: 5432
    database: nirdb
    username: postgres
    password: postgres

test:
  <<: *default
  database: nir_test

production:
  <<: *default
  database: nir_production
  username: nir
  password: <%= ENV["NIR_DATABASE_PASSWORD"] %>
